[KYUUBI #2385] Export JAVA_HOME. It seems TravisCI stopped doing it recently
### _Why are the changes needed?_

Many builds at TravisCI recently failed due to error like
```
- hive process builder *** FAILED ***

  org.apache.kyuubi.KyuubiSQLException: JAVA_HOME is not set! For more information on installing and configuring JAVA_HOME, please visit https://kyuubi.apache.org/docs/latest/deployment
```

It seems TravisCI stopped exporting JAVA_HOME ...

### _How was this patch tested?_

TravisCI build should pass

Closes #2385 from martin-g/manually-export-java-home-travis.

Closes #2385

5c2a3f62 [Martin Tzvetanov Grigorov] The correct path for the JDK 8 installation is /usr/lib/jvm/adoptopenjdk-8-hotspot-arm64
78bac049 [Martin Tzvetanov Grigorov] Export JAVA_HOME. It seems TravisCI stopped doing it recently

Authored-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
Signed-off-by: Fei Wang <fwang12@ebay.com>