[KYUUBI #2310] Make ranger extension work with mac m1
### _Why are the changes needed?_

Update jna version to 5.7.0

Before
```
java.lang.UnsatisfiedLinkError: /Users/cathy/Library/Caches/JNA/temp/jna8371704468821938112.tmp: dlopen(/Users/cathy/Library/Caches/JNA/temp/jna8371704468821938112.tmp, 0x0001): tried: '/Users/cathy/Library/Caches/JNA/temp/jna8371704468821938112.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
  at java.lang.ClassLoader$NativeLibrary.load(Native Method)
  at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
  at java.lang.Runtime.load0(Runtime.java:811)
  at java.lang.System.load(System.java:1088)
  at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1012)
  at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
  at com.sun.jna.Native.<clinit>(Native.java:195)
  at com.kstruct.gethostname4j.Hostname$UnixCLibrary.<clinit>(Hostname.java:12)
  at com.kstruct.gethostname4j.Hostname.getHostname(Hostname.java:30)

```

The 5.7.0 version is from https://github.com/mattsheppard/gethostname4j/pull/8

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

Closes #2310 from ulysses-you/m1-jna.

Closes #2310

3706c871 [ulysses-you] ordering
b9b4e929 [ulysses-you] fix

Authored-by: ulysses-you <ulyssesyou18@gmail.com>
Signed-off-by: ulysses-you <ulyssesyou@apache.org>