[KYUUBI #6047] [CI] Free up disk space
# :mag: Description
## Issue References 🔗

I saw [the K8s IT](https://github.com/apache/kyuubi/actions/runs/7776268590/job/21203214430?pr=6045) failed with

```
Error: No space left on device : '/home/runner/runners/2.312.0/_diag/pages/131e7057-723d-4281-b296-b876237f4318_21774d93-c106-57cd-810b-f0e6bf96d865_1.log'
```

## Describe Your Solution 🔧

Borrow the solution from Apache Spark, just uninstall the un-used large pre-installed packages.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Test Plan 🧪

Wait CI report

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

Closes #6047 from pan3793/ci-space.

Closes #6047

272df2790 [Cheng Pan] nit
8c78115a4 [Cheng Pan] nit
a9c8b035c [Cheng Pan] nit
ab4c3e461 [Cheng Pan] keep jdk8
9d1ec4e44 [Cheng Pan] extend
47f90b95e [Cheng Pan] nit
30b82cdf0 [Cheng Pan] fix
352689f89 [Cheng Pan] [CI] Free up disk space for K8s IT

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: Cheng Pan <chengpan@apache.org>