[HADP-44790] Revert "[KYUUBI #2104] Kill yarn job using yarn client API when kyuubi engine" to prevent conflicts
This reverts commit ffdd665f79c0bc3145a516a1732ff0b93c61b4e5.

To prevent conflicts with ebay managed hadoop libarary.
```
23:58:41.106 INFO org.apache.kyuubi.operation.LaunchEngine: Processing b_stf's query[2fb5fd8f-c116-474c-bbb2-a3bc8cf595e4]: RUNNING_STATE -> ERROR_STATE, statement: LAUNCH_ENGINE, time taken: 0.105 seconds
Error: Error operating UNKNOWN_OPERATION: java.lang.NoClassDefFoundError: org/apache/hadoop/yarn/client/api/YarnClient
	at org.apache.kyuubi.engine.spark.SparkProcessBuilder.getYarnClient(SparkProcessBuilder.scala:50)
	at org.apache.kyuubi.engine.spark.SparkProcessBuilder.<init>(SparkProcessBuilder.scala:48)
	at org.apache.kyuubi.engine.EngineRef.$anonfun$create$1(EngineRef.scala:193)
	at org.apache.kyuubi.engine.EngineRef.tryWithLock(EngineRef.scala:163)
	at org.apache.kyuubi.engine.EngineRef.create(EngineRef.scala:177)
	at org.apache.kyuubi.engine.EngineRef.$anonfun$getOrCreate$1(EngineRef.scala:253)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.kyuubi.engine.EngineRef.getOrCreate(EngineRef.scala:253)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1(KyuubiSessionImpl.scala:128)
	at org.apache.kyuubi.session.KyuubiSessionImpl.$anonfun$openEngineSession$1$adapted(KyuubiSessionImpl.scala:127)
	at org.apache.kyuubi.ha.client.ZooKeeperClientProvider$.withZkClient(ZooKeeperClientProvider.scala:104)
	at org.apache.kyuubi.session.KyuubiSessionImpl.openEngineSession(KyuubiSessionImpl.scala:127)
	at org.apache.kyuubi.operation.LaunchEngine.$anonfun$runInternal$1(LaunchEngine.scala:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.yarn.client.api.YarnClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more (state=,code=0)
Beeline version 1.4.0.1.3.0 by Apache Kyuubi (Incubating)
```