[KYUUBI #2427][FOLLOWUP] Flaky test: deregister when meeting specified exception
### _Why are the changes needed?_
https://github.com/apache/incubator-kyuubi/issues/2427

master nightly [log](https://github.com/apache/incubator-kyuubi/actions/runs/2273625147) :
```
04:23:04.585 Executor task launch worker for task 0.0 in stage 2.0 (TID 2) ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
org.apache.spark.SparkArithmeticException: Casting 2.147483648E9D to "INT" causes overflow. To return NULL instead, use 'try_cast'. If necessary set "spark.sql.ansi.enabled" to false to bypass this error.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.castingCauseOverflowError(QueryExecutionErrors.scala:95) ~[spark-catalyst_2.12-3.3.0-SNAPSHOT.jar:3.3.0-SNAPSHOT]
````

[[SPARK-39007](https://issues.apache.org/jira/browse/SPARK-39007)][SQL] Use double quotes for SQL configs in error messages

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

Closes #2568 from cxzl25/KYUUBI-2427-FOLLOWUP.

Closes #2427

0f9fb283 [sychen] fix UT

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: Kent Yao <yao@apache.org>