[KYUUBI #6081] RESTful client should retry on UnknownHostException
# :mag: Description
## Issue References 🔗

When deploying Kyuubi as StatefulSet on Kubernetes, during the rolling upgrade, the Pod stops and creates one by one, and there are a few durations that the Pod is not available, then `UnknownHostException` is returned.

```
2024-02-23 23:04:45 [ERROR] [KyuubiRestFrontendService-122] org.apache.kyuubi.client.RestClient#189 - Error:
java.net.UnknownHostException: kyuubi-2.kyuubi-headless.spark.svc.cluster.local
	at java.net.InetAddress$CachedAddresses.get(InetAddress.java:764) ~[?:1.8.0_382]
	...
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.kyuubi.client.RestClient.doRequest(RestClient.java:181) ~[kyuubi-rest-client-1.8.0.17.jar:1.8.0.17]
	at org.apache.kyuubi.client.RestClient.get(RestClient.java:80) ~[kyuubi-rest-client-1.8.0.17.jar:1.8.0.17]
	...
	at org.apache.kyuubi.client.BatchRestApi.getBatchLocalLog(BatchRestApi.java:104) ~[kyuubi-rest-client-1.8.0.17.jar:1.8.0.17]
	at org.apache.kyuubi.server.api.v1.InternalRestClient.$anonfun$getBatchLocalLog$1(InternalRestClient.scala:57) ~[kyuubi-server_2.12-1.8.0.17.jar:1.8.0.17]
	at org.apache.kyuubi.server.api.v1.InternalRestClient.withAuthUser(InternalRestClient.scala:81) ~[kyuubi-server_2.12-1.8.0.17.jar:1.8.0.17]
	at org.apache.kyuubi.server.api.v1.InternalRestClient.getBatchLocalLog(InternalRestClient.scala:57) ~[kyuubi-server_2.12-1.8.0.17.jar:1.8.0.17]
	at org.apache.kyuubi.server.api.v1.BatchesResource.$anonfun$getBatchLocalLog$4(BatchesResource.scala:424) ~[kyuubi-server_2.12-1.8.0.17.jar:1.8.0.17]
```

## Describe Your Solution 🔧

Treat `UnknownHostException` as a retriable exception to tolerant the transient Pod FQDN not available cases during rolling upgrade on K8s.

## Types of changes :bookmark:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Test Plan 🧪

Pass GA.

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

Closes #6081 from pan3793/unknown-host.

Closes #6081

0df3883e6 [Cheng Pan] RESTful client should retry on UnknownHostException

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: Cheng Pan <chengpan@apache.org>